# Generated by Django 5.2.12 on 2026-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sequence_no',
            field=models.IntegerField(default=0),
        ),
    ]
