# Generated by Django 5.2.12 on 2026-03-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_sequence_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
