# Generated by Django 5.2.12 on 2026-04-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcall',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
